apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: devops
  labels:
    app: my-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
      - name: python-app
        image: nohaalmetwally/python-repo:latest
        ports:
        - containerPort: 8000
