apiVersion: v1
kind: Service

metadata:
  name: my-app-service
  namespace: devops

spec:
  type: LoadBalancer
  ports:
    - port: 8000
      nodePort: 30055
      protocol: TCP

  selector:
    app: my-pod
